# ==========================================
# 1. إعدادات منفذ تشغيل السيرفر
# ==========================================
server.port=8083

# ==========================================
# 2. إعدادات لوحة تحكم قاعدة البيانات (H2 Console)
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# 3. إعدادات الاتصال بقاعدة البيانات في الذاكرة (In-Memory)
# ==========================================
spring.datasource.url=jdbc:h2:mem:medibook_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# 4. إعدادات معالج الجداول والـ JPA (Hibernate)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# 5. حل مشكلة التوقيت والـ SQL
# ==========================================
spring.jpa.defer-datasource-initialization=true


# المسار الذي ستدخله من المتصفح (http://localhost:8083/h2-console)